import Head from "next/head";
import { useRouter } from "next/router";
import { useContext } from "react";
import Main from "../../components/Main";
import { AuthContext } from "../../contexts/AuthContext";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const { currentUser } = useContext(AuthContext);

  const ProtectedRoute = ({ children }) => {
    if (!currentUser) {
      router.push("/login");
      return null;
    }
    return children;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ProtectedRoute>
          <Main />
        </ProtectedRoute>
      </div>
    </>
  );
}
